### ISSUE TITLE
UnsatisfiedLinkError on ch.qos.logback.classic.Logger

### ISSUE THREAD

**Issue by spiritokko** [aclement/spring-boot-graal-feature#2]
Hello,
I'm trying to reuse your library on one of my spring boot applications. After some tweaks I've been able to generate native image and start it successfully.
After the web server is up & running, at each request I get the following error:

Exception in thread "reactor-http-nio-2" java.lang.UnsatisfiedLinkError: sun.reflect.Reflection.getCallerClass(I)Ljava/lang/Class; [symbol: Java_sun_reflect_Reflection_getCallerClass or Java_sun_reflect_Reflection_getCallerClass__I]
	at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
	at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
	at sun.reflect.Reflection.getCallerClass(Reflection.java)
	at ch.qos.logback.classic.spi.PackagingDataCalculator.populateFrames(PackagingDataCalculator.java:85)
	at ch.qos.logback.classic.spi.PackagingDataCalculator.calculate(PackagingDataCalculator.java:58)
	at ch.qos.logback.classic.spi.ThrowableProxy.calculatePackagingData(ThrowableProxy.java:142)
	at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:122)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:419)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
	at ch.qos.logback.classic.Logger.log(Logger.java:765)
	at io.netty.util.internal.logging.LocationAwareSlf4JLogger.log(LocationAwareSlf4JLogger.java:46)
	at io.netty.util.internal.logging.LocationAwareSlf4JLogger.warn(LocationAwareSlf4JLogger.java:209)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:908)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)

I was wondering if this has to do with missing entries in reflect.json file.
thanks for your support

**Comment by guanchao-yang** [comment]
We see the same problem today with Spring Boot deployment too using GraalVM.

**Comment by spiritokko** [comment]
I bypassed the issue creating a substitution directly in graal substratevm. The problem is that the method sun.reflect.Reflection.getCallerClass(int) is no more supported in Java8, hance not implemented in substratevm.
The workaround I used is to force the substitution of this method via this implementation

`@Substitute
    public static Class<?> getCallerClass(int depth) {
        return null;
  }`

in the file com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_jdk_internal_reflect_Reflection.java
within graal/substratevm

Another possible approach is to try update the logback library: as you can see the current version 1.2.3 is a bit old and the current alpha implementation of the PackagingDataCalculator class (that triggers the getCallerClass call) does not contain reference to this method anymore:

`if (GET_CALLER_CLASS_METHOD_AVAILABLE) {
                //callerClass = Reflection.getCallerClass(localFirstCommon + i - missfireCount + 1);
  }`

 I used as a reference this thread: https://github.com/oracle/graal/issues/748

**Comment by aclement** [comment]
Simplest thing to do is remove logback and then you'll see the real problem that is causing it to need to do the digging for stack trace info.
